Постройте мелкие сетки на гридах для подходящих компонентов
htmlacademy-htmlcss/1896209-sedona-33 pull request #12
Opened 2022-02-20 16:08 UTC by ValeriaGarceva

Список преимуществ начал мне поддаваться, но все равно до конца не получилось доработать. Мне кажется, что я явно незаконным образом привела этот список в данный вид)) И еще в html  я обернула три последних элемента списка в див, чтобы можно было поработать в общем со строкой, а валидатор указал, что див в ol быть включен не может.( но менять я ничего не стала, потому что не понимаю на что help )

2022-02-20 16:15 UTC, ValeriaGarceva commented
А еще у меня проблема с цветом заднего фона в списке преимуществ. В фигме указывается в hex цвет с процентом прозрачности, как я поняла. Я пыталась на каких-то сайтах, где цвет можно перевести в нужную форму, получить эти заветные 6 символов. Но цвета все равно другие.

2022-02-21 17:07 UTC, what1s1ove requested changes
цвет указан тут - 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/42296182/154999893-e5424504-97a9-4a5d-b66f-cf2fdce09dda.png">
используй его

2022-02-21 17:07 UTC, what1s1ove commented on index.html
> +            </div>
все правильно тебе говорит валидатор, внутри `ol` могут быть только `li` (на первом уровне)

2022-02-21 17:07 UTC, what1s1ove commented on index.html
> +            </div>
Тебе нужен один список 

```html
<ul class="advantages-list">
  <li class="advantages-item real-city">
    <h3 class="advantages-title true-city">Настоящий городок</h3>
  </li>
  <li class="advantages-item photo-city">
    <img class="photo" src="images/photo-city.jpg" alt="Фото городка.">
  </li>
  <li class="advantages-item housing">
    <h3 class="advantages-title house">Жильё</h3>
  </li>
  <li class="advantages-item food">
    <h3 class="advantages-title meal">Еда</h3>
  </li>
  <li class="advantages-item souvenirs">
    <h3 class="advantages-title souvenir">Сувениры</h3>
  </li>
  <li class="advantages-item diablo-bridge">
    <h3 class="advantages-title bridge-diablo">Там есть мост дьявола</h3>
  </li>
  <li class="advantages-item photo-bridge">
    <img class="photo" src="images/photo-bridge.jpg" alt="Фото моста дьявола.">
  </li>
  <li class="advantages-item square">
    <h3 class="advantages-title place">Небольшая площадь</h3>
  </li>
  <li class="advantages-item road">
    <h3 class="advantages-title way">Красивая дорога</h3>
  </li>
  <li class="advantages-item tourists">
    <h3 class="advantages-title tourer">Мало<br> туристов</h3>
  </li>
</ul>
```

(разметка, классы, это просто пример). Накинуть на весь список `display: grid`, сделать нужно количество колонок и строк. А дальше сказать айтемам, чтобы они занимали свои колонки. Например это для `.photo-city`

```css
.photo-city {
    grid-column: 2/4;
    grid-row: 1/2;
}
```

2022-02-22 12:34 UTC, closed without merging